db:
 build: ./db
 ports:
    - "3307:3306"
api:
  build: ./api
  ports:
   - "8080:8080"
   volumes:
       - ./api:/api
   command: /bin/sh /api/run.sh
   links:
       - db
web:
  build: ./web
  ports:
   - "4040:4040"
  volumes:
   - ./web:/web
  links:
   - api